-- phpMyAdmin SQL Dump
-- version 4.9.7
-- https://www.phpmyadmin.net/
--
-- Host: localhost:3306
-- Generation Time: Aug 12, 2022 at 12:22 AM
-- Server version: 10.5.16-MariaDB
-- PHP Version: 7.4.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `nuestrav_prod`
--

-- --------------------------------------------------------

--
-- Table structure for table `vln_wines`
--

DROP TABLE IF EXISTS `vln_wines`;
CREATE TABLE IF NOT EXISTS `vln_wines` (
  `id` int(3) NOT NULL AUTO_INCREMENT,
  `name` varchar(50) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `image_url` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `status` varchar(20) COLLATE utf8mb4_unicode_520_ci DEFAULT 'draft',
  `description_es` varchar(1000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `description_en` varchar(1000) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `grape_varietal_es` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `origin_country_es` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `food_pairing_es` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `awards_es` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `grape_varietal_en` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `origin_country_en` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `food_pairing_en` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `awards_en` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `award_image` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `bottle_price_es` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `box_price_es` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `bottle_price_en` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `box_price_en` varchar(10) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `datasheet_es` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  `datasheet_en` varchar(500) COLLATE utf8mb4_unicode_520_ci DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_520_ci;

--
-- Dumping data for table `vln_wines`
--

INSERT INTO `vln_wines` (`id`, `name`, `image_url`, `status`, `description_es`, `description_en`, `grape_varietal_es`, `origin_country_es`, `food_pairing_es`, `awards_es`, `grape_varietal_en`, `origin_country_en`, `food_pairing_en`, `awards_en`, `award_image`, `bottle_price_es`, `box_price_es`, `bottle_price_en`, `box_price_en`, `datasheet_es`, `datasheet_en`) VALUES
(1, 'Princesa', '/wp-content/uploads/media/Princesa-Botella-sombra-1.png', 'published', 'Un vino de uvas Cabernet Sauvignon seleccionadas y una esmerada crianza en barrica de roble francés. El resultado: Unos aromas vívidos aunque maduros, un paladar jovial pero distinguido, un cuerpo esbelto y a la vez elegante. Princesa es un vino sofisticado que hace especial el momento.', 'A Cabernet Sauvignon wine made from selected grapes and a careful aging in French oak barrels. The result: Vivid and ripe aromas, a jovial yet distinguished palate, slender and at the same time elegant body. Princesa is a sophisticated wine that makes the moment special.', 'Cabernet Sauvignon', 'Valles de Baja California, Mexico', 'Ideal con un ceviche de pescado, ensalada con arándano y queso de cabra o un pollo frito con chutney de cereza', 'PLATA | Añada 2012\n15 Pacific Rim Wine Competition', 'Cabernet Sauvignon', 'Baja California Valleys, Mexico', 'Great with primerib, blue cheeseburger and hotdogs wrapped in panchetta.', 'SILVER | Vintage 2012\n15 Pacific Rim Wine Competition', '/wp-content/uploads/media/MEDALLA-Princesa-PacificRim-min.png', '350.00', '4200.00', '10.00', '120.00', '/wp-content/uploads/media/2022/08/Princesa-2017-FichaTécnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Princesa-2017-FichaTecnica-NotaCata-Ing.pdf'),
(2, 'Juglar', '/wp-content/uploads/media/Juglar-Botella-sombra-1.png', 'published', 'Un artista del medievo que poseía los dones de la música, el entretenimiento y la poesía. La personalidad de este vino de uva Carignan proviene de las nobles vides de un viñedo de temporal en el Ejido del Porvenir y que gracias a nuestro estilo de vinificación expresa todo su potencial. Juglar es un vino que hará entretenido cualquier evento.', 'A medieval artist who mastered the gifts of music, entertainment and poetry. This Carignan wine´s personality comes from the noble vines of a temporary vineyard in the Ejido del Porvenir and thanks to our winemaking style, it expresses its full potential. Juglar is a wine that will make any event entertaining.', 'Carignan', 'Valles de Baja California, Mexico', 'Acompaña un espaghetti a la bolonesa o una pizza.', 'PLATA | Añada 2013/12/10\n2016 San Diego International Wine & Spirits Challenge\n2016 Pacific Rim Wine Competition\n2015 Pacific Rim Wine Competition XXII Concurso Internacional Ensenada Tierra del Vino UABC', 'Carignan', 'Baja California Valleys, Mexico', 'Pairs well with spaghetti bolognese or even a crusty pizza.', 'SILVER | Vintage 2013/12/10\n2016 San Diego International Wine & Spirits Challenge\n2016 Pacific Rim Wine Competition\n2015 Pacific Rim Wine Competition XXII Concurso Internacional Ensenada Tierra del Vino UABC', '/wp-content/uploads/media/MEDALLAS-Juglar-6-min.png', '400.00', '4800', '15.00', '180.00', '/wp-content/uploads/media/2022/08/Juglar-2015-FichaTécnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Juglar-2015-FichaTecnica-NotaCata-Ing.pdf'),
(3, 'Cantiga', '/wp-content/uploads/media/Cantiga-Botella-sombra-1.png', 'published', 'Es un poema musical que fluye hacia el espíritu. Cantiga es una composición de pasión, terruño y uvas excepcionales, es una oda al Chenin Blanc. Presenta un balanceado perfil a frutas y especias, reflejo de las características de la uva proveniente de la Cañada de Guadalupe en el Valle de Guadalupe. Cantiga es una bella composición al paladar.', 'It is a musical poem that flows into the spirit. Cantiga is a composition of passion, earth and exceptional grapes, it is an ode to Chenin Blanc. It presents a balanced profile of fruits and spices, reflecting the character of this grape from the Cañada de Guadalupe in Valle de Guadalupe. Cantiga is a beautiful composition on the palate', '100% Chenin Blanc', 'Valles de Baja California, Mexico', 'Ideal con un ceviche de pescado, ensalada con arándano y queso de cabra o un pollo frito con chutney de cereza.', 'PLATA | Añada 2015\n2016 Pacific Rim Wine Competition', '100% Chenin Blanc', 'Baja California Valleys, Mexico', 'Prefect for a fish filet, Thai curry or spaghetti with butter sauce', 'SILVER | Vintage 2015\n2016 Pacific Rim Wine Competition', '/wp-content/uploads/media/MEDALLA-Cantiga-PacificRim-min.png', '300.00', '3600.00', '12.00', '144.00', '/wp-content/uploads/media/2022/08/Cantiga-2021-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Cantiga-2021-FichaTecnica-NotaCata-Ing.pdf'),
(4, 'Adalid', '/wp-content/uploads/media/Adalid-Botella-sombra-1.png', 'published', 'Un vino de uva Tempranillo cuya personalidad única refleja la fruta selecta y nuestro estilo de vinificación. Aroma sutil a frutos oscuros, cueros, especias. Paladar voluptuoso y sedoso, reflejo de su terruño único: La Cañada del Trigo en el Valle de Guadalupe. Adalid es un vino que encabezará grandes ocasiones.', 'It is a Tempranillo wine whose unique personality reflects our selected grapes and our winemaking style. Subtle aromas of dark fruits, leather, spices. Voluptuous and silky palate, a reflection of its unique terroir: La Cañada del Trigo in the Valle de Guadalupe. Adalid is a wine that will headline great occasions.', '100 % Tempranillo', 'Valles de Baja California, Mexico', 'Acompaña un espaghetti a la bolonesa o una pizza', 'ORO | Añada 2013\nXXIV Concurso Internacional Ensenada Tierra del Vino UABC', '100 % Tempranillo', 'Baja California Valleys, Mexico', 'Great with a slow cooked piglet or grilled flank steak.', 'GOLD | Vintage 2013\nXXIV Concurso Internacional Ensenada Tierra del Vino UABC', '/wp-content/uploads/media/MEDALLA-Adalid-Oro-min.png', '400.00', '4800.00', '14.00', '168.00', '/wp-content/uploads/media/2022/08/Adalid-2019-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Adalid-2019-FichaTecnica-NotaCata-Ing.pdf'),
(5, 'Alabardero', '/wp-content/uploads/media/Alabardero-Botella-sombra-1.png', 'published', 'Es un soldado digno de ser guardia de reyes. Alabardero es un vino con un porte que hace honor a su nombre. Uvas selectas Cabernet Sauvignon y Tempranillo con el carácter único de esta tierra que tras los cuidados de nuestra bodega, dan vida a este vino cuya personalidad es una magnífica compañía al paladar.', 'He is a soldier worthy of being a guard of kings. This is a wine with a stance that lives up to its name. After our attentive care a selection of Cabernet Sauvignon and Tempranillo grapes reflecting the unique character of this land, give birth to this wine whose personality is a magnificent company when palate.', 'Cabernet Sauvignon y Tempranillo', 'Valles de Baja California, Mexico', 'Ideal con un ceviche de pescado, ensalada con arándano y queso de cabra o un pollo frito con chutney de cereza', 'ORO | Añada 2017/13\nXXVII Concurso Internacional Ensenada Tierra del Vino UABC\n2017 San Diego International Wine & Spirits Challenge', 'Cabernet Sauvignon y Tempranillo', 'Baja California Valleys, Mexico', 'Will be a great companion for a slow roast piglet, a skirt steak, lamb chomps or pork rind tacos.', 'GOLD | Vintage 2017/13\nXXVII Concurso Internacional Ensenada Tierra del Vino UABC\n2017 San Diego International Wine & Spirits Challenge', '/wp-content/uploads/media/MEDALLAS-Alabardero-Oro2-min.png', '410.00', '4920.00', '14.00', '168.00', '/wp-content/uploads/media/2022/08/Alabardero-2019-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Alabardero-2019-FichaTecnica-NotaCata-Ing.pdf'),
(6, 'Reserva', '/wp-content/uploads/media/Reserva-Botella-sombra-1.png', 'published', 'Reserva proviene de una cosecha excepcional, de las que no se dan todos los años. Es un claro testimonio de las características específicas de un Cabernet Sauvignon. Con una estructura sólida, equilibrada y de taninos elegantes, este vino fue llevado a su mejor expresión a través de 12 meses de añejamiento en barrica de roble francés y 24 meses en botella. Potencial de guarda: 20 años.', 'Reserva comes from an exceptional harvest of Cabernet Sauvignon, one of which is not produced every year. It is a clear testament to the specific characteristics of this grape. With a solid, balanced structure and elegant tannins, this wine was taken to its best expression through 12 months of aging in French oak barrels and 24 months in bottle. Aging potential: 20 years.', 'Cabernet Sauvignon', 'Valles de Baja California, Mexico', 'Acompaña muy bien cortes como el tomahawk, ribeye o rinodada de cabrito', 'PLATA | Añada 2018\n2020 Concours Mondial de Bruxelles', 'Cabernet Sauvignon', 'Baja California Valleys, Mexico', 'An excellent companion for a Tomahawk, a rib eye, or a grilled goat.', 'SILVER | Vintage 2018\n2020 Concours Mondial de Bruxelles', '/wp-content/uploads/media/MEDALLA-Reserva-Bruselas-min.png', '430', '00', '15.00', '00', '/wp-content/uploads/media/2022/08/Reserva-2018-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Reserva-2018-FichaTecnica-NotaCata-Ing-1.pdf'),
(7, 'Merlot', '/wp-content/uploads/media/Merlot-Botella-sombra-1.png', 'published', 'Este es un elegante vino que refleja las bondades características del Valle de Guadalupe. Su esmerada elaboración hace que destaquen en boca alegres matices de cereza y fresa. Un vino estructurado de cuerpo untuoso y taninos redondos que se deja maridar deliciosamente.', 'This is an elegant wine that reflects the characteristic qualities of the Valle de Guadalupe. Its meticulous preparation makes cheerful cherry and strawberry nuances stand out in the mouth. A structured wine with an unctuous body and round tannins that can be paired deliciously.', 'Carignan', 'Valles de Baja California, Mexico', 'Acompaña un espaghetti a la bolonesa o una pizza.', 'PLATA | Añada 2019\n2021 Mexico International Wine Competition', 'Carignan', 'Baja California Valleys, Mexico', 'Pairs deliciously with a ribeye steak on the grill or an arrachera.', 'SILVER | Vintage 2019\n2021 Mexico International Wine Competition', '/wp-content/uploads/media/MEDALLA-Merlot-Plata-min.png', '430.00', '5160.00', '15.00', '180.00', '/wp-content/uploads/media/2022/08/Merlot-2019-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Merlot-2019-FichaTecnica-NotaCata-Ing-1.pdf'),
(8, 'Mision', '/wp-content/uploads/media/Mision-Botella.png', 'published', 'Heredera de las uvas originales traídas por los Jesuitas durante la Colonia. Las cepas que dan origen a este vino se crían en un lomerío altanero del Valle de Guadalupe siguiendo la antigua usanza, sin espaldar. Resultado: Un vino único lleno de personalidad de color rubí límpido. Una nariz fresca con notas de frutos rojos que se reafirman en boca. Un cuerpo sorprendente que persiste con frescura y amabilidad.', 'Heir to the original grapes brought from Spain by the Jesuits during the Colony. The particular vines that give birth to this wine are grown in a hilly area in the Guadalupe Valley following the old cultivation way, without backing. The result: a unique wine full of personality with a clear ruby color. A fresh nose with notes of red fruits that reaffirm in the mouth. A surprising body that lingers with freshness and kindness.', 'Cabernet Sauvignon', 'Valles de Baja California, Mexico', 'Acompaña muy bien cortes como el tomahawk, ribeye o rinodada de cabrito.', '', 'Cabernet Sauvignon', 'Baja California Valleys, Mexico', 'A perfect companion for a slowly cooked goat, a pozole, menudo or prepared clams.', '', '', '300.00', '3600.00', '12.00', '144.00', '/wp-content/uploads/media/2022/08/Mision-2020-FichaTecnica-NotaCata-Esp.pdf', '/wp-content/uploads/media/2022/08/Mission-2020-FichaTecnica-NotaCata-Ing.pdf'),
(9, 'NEBBIOLO', '/wp-content/uploads/media/2022/08/Nebbiolo-Botella.png', 'published', 'Una uva que exige cuidados fuera de lo común pero que ofrece grandes recompensas. En la Nuestra hemos logrado un vino que recompensa el olfato y el paladar, de carácter equilibrado que brinda alegres matices de cereza y fresa madura con dejos de chocolate. Sus taninos crean una elegancia discreta que le permiten alcanzar un amplio rango de deliciosos maridajes.', 'This grape requires an out of the ordinary care but offers great rewards. At La Nuestra we\'ve achieved a wine that rewards the nose and the palate with a balanced character, bringing joyful cherry notes as well as mature strawberry with a hint of chocolate. Its tannins create a discreet elegance allowing this wine to reach a wide range of delicious pairings.', 'Tinto varietal de origen', 'Valles de Guadalupe, México', 'Gnocci con jabalí, tsic de venado, chuletas de cordero', '', 'Red single origin monovarietal', 'Valle de Guadalupe, México', 'Wild boar Gnocci, Venison stew, lamb chops', '', '', '350.00', '4200.00', '20.00', '240.00', '/wp-content/uploads/media/2022/08/Nebbiolo-2021-FichaTecnica-NotaCata-Esp-1.pdf', '/wp-content/uploads/media/2022/08/Nebbiolo-2021-FichaTecnica-NotaCata-Ing-2.pdf');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
